# Generated by Django 3.0.3 on 2020-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='created_at',
            new_name='check_time',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='text',
            new_name='keyword',
        ),
        migrations.AddField(
            model_name='rank',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rank',
            name='target_post_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='rank',
            name='temp_data',
            field=models.TextField(default='', null=True),
        ),
    ]
