# Generated by Django 3.0.3 on 2020-02-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20200207_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='check_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='keyword',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='target_post_url',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='temp_data',
        ),
    ]
